# Generated by Django 3.1.7 on 2021-02-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('host', models.TextField()),
                ('url', models.TextField()),
                ('Type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('Type', models.TextField()),
                ('description', models.TextField()),
                ('source', models.TextField()),
                ('origin', models.TextField()),
                ('contentType', models.TextField()),
                ('content', models.TextField()),
                ('categories', models.TextField()),
                ('commentLink', models.TextField()),
                ('commentCount', models.IntegerField()),
                ('pageSize', models.IntegerField()),
                ('published', models.BooleanField()),
                ('visibility', models.TextField()),
                ('unlisted', models.BooleanField()),
            ],
        ),
    ]
