# Generated by Django 3.1.7 on 2021-04-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.TextField(choices=[('text/plain', 'Choice1'), ('text/markdown', 'Choice2')], default='text/plain'),
        ),
    ]
