# Generated by Django 3.1.7 on 2021-03-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='id',
        ),
        migrations.AlterField(
            model_name='node',
            name='host',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
