# Generated by Django 3.1.7 on 2021-02-23 02:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='display_name',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_id',
            new_name='id',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('contentType', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.TextField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.author')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.post')),
            ],
        ),
    ]
