# Generated by Django 3.1.7 on 2021-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_auto_20210407_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
