# Generated by Django 3.1.7 on 2021-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_auto_20210228_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.TextField(default='comment'),
        ),
    ]
