# Generated by Django 3.1.7 on 2021-04-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_auto_20210408_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='recieve',
            field=models.BooleanField(default=False),
        ),
    ]
