# Generated by Django 3.1.7 on 2021-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0005_auto_20210301_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.TextField(choices=[('text/plain', 'Choice1'), ('text/markdown', 'Choice2'), ('application/base64', 'Choice3'), ('image/png;base64', 'Choice4'), ('image/jpeg;base64', 'Choice5')]),
        ),
    ]
