# Generated by Django 3.1.7 on 2021-03-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0007_auto_20210302_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Type',
            new_name='type',
        ),
    ]
